events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Server 1: Chạy site1 (domain1.com hoặc localhost) + API Node-RED
    server {
        listen 80;
        server_name localhost domain1.com www.domain1.com;

        location / {
            root /usr/share/nginx/html/site1;
            index index.html;
        }

        # Route gọi API Node-RED
        location /api/tacke {
            proxy_pass http://nodered:1880/api/tacke;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Server 2: Chạy site2 (domain2.com)
    server {
        listen 80;
        server_name domain2.com www.domain2.com;

        location / {
            root /usr/share/nginx/html/site2;
            index index.html;
        }
    }
}
